### ISSUE TITLE
_boom module name

### ISSUE THREAD

**Issue by AndreaCrotti** [tarekziade/boom#31]
I would like to use boom as a library instead of a script to collect the results smartly and produce some graphs.

The only thing which is a bit puzzling though is that the module I should import everything from is named _boom, which conventionally should mean it's private, right?
Is there any reason for that?

**Comment by tarekziade** [comment]
Thanks for your contribs @AndreaCrotti - boom 0.9 is out with them

Happy to see what we could do next to improve the tool
