### ISSUE TITLE
BSI "Hahahaha" is hahahaha

### ISSUE THREAD

**Issue by pfalcon** [tarekziade/boom#44]
I'm using boom to do real load testing on my server - using multi-megabyte response bodies, and post-hook to validate that they contain what's expected and not garbage. At the end I get:

~~~~
RPS               		9
BSI              		Hahahaha
~~~~

I tell ya, there's nothing "Hahahaha" in serving nine 10-megabyte dynamically generated requests per second. So, please consider adjusting BSI for transfer size. (Oh and btw, unlike ab, boom doesn't even report request transfer sizes, so please consider showing that.)

**Comment by hanleyhansen** [comment]
Logic status that `Hahahaha` is for anything lower than 50rps

@pfalcon would you be happier with something like `< 50rps :(`

I feel `Hahahaha` gives the impression that it's so fast that it was hilarious and it this case it's slowness that causes the `Hahahaha`

**Comment by hanleyhansen** [comment]
Or maybe just this:


```python
print('BSI              \t\t:(')
```

**Comment by hanleyhansen** [comment]
This has been addressed and merged. Closing.

Ref: https://github.com/tarekziade/boom/pull/58
