### ISSUE TITLE
Release current code to pypi

### ISSUE THREAD

**Issue by marcinkuzminski** [tarekziade/boom#50]
Hi,

0.9 version introduces some nice changes, is there a plan to make a release out of it ?

**Comment by novocaine** [comment]
+1

**Comment by EmilStenstrom** [comment]
+1

**Comment by tarekziade** [comment]
Sorry people, I am lacking bandwidth right now. Anyone would be willing to help me manage this project ? @marcinkuzminski  ?

**Comment by marcinkuzminski** [comment]
sorry i'm also totally without capacity to do this.

**Comment by hanleyhansen** [comment]
@tarekziade i'll gladly help you manage this project. i'm a long time ab user and once i found boom i was hooked. i'll be using it exclusively going forward.

**Comment by tarekziade** [comment]
@hanleyhansen very cool, thanks!

I have just pushed 0.9  https://pypi.python.org/pypi/boom/0.9

Maybe we can talk via email to discuss what we should do next for the 1.0 release
please send me an email tarek_at_ziade.org

**Comment by marcinkuzminski** [comment]
@tarekziade awesome ! thanks for the release
