### ISSUE TITLE
How can I test "https" requests

### ISSUE THREAD

**Issue by manivannan-g** [tarekziade/boom#55]
I'm using boom for a while now with http://hostname requests, I needed to test https://hostname/uri as well. I was getting **InsecurePlatformWarning** and **SNIMissingWarning**. Post installing libssl1.0.0, pyopenssl. I'm just getting bad handshake: Error. Can you please help ?

**Comment by hanleyhansen** [comment]
@manivannan-g what platform are you? can you post the `boom` command in here?

**Comment by vstoykov** [comment]
This is because you are using old Python 2.7 (<2.7.9). If you install boom on Python 2.7.9+ or Python 3 you will not have this problem.

**Comment by hanleyhansen** [comment]
Closing this issue since it's been almost a month and no response. Please reopen with more details if there's still a problem.
