### ISSUE TITLE
moving from gevent to asyncio ?

### ISSUE THREAD

**Issue by tarekziade** [tarekziade/boom#60]
Asyncio is probably mature enough now so we could move to it, since most of its features are backported to py2.7. 

I am also wondering if we could get rid of requests as well, making boom a vanilla Python script, so easier for people to install.

**Comment by alanjds** [comment]
Is ``requests`` any burden?

**Comment by Hellowlol** [comment]
Have there been done any attempt to get more performance out of boom. Right now its pretty slow, it caps around 550 rps while i can use process and threads to push 4.9 k rps using urllib3. Using processes and human_curl caps around 8.5 k rps.

requests is pretty slow.

**Comment by tarekziade** [comment]
No I have not really tried to tune it since it was good enough for the job. But if we can make it faster I am all for it :)

**Comment by tarekziade** [comment]
@Hellowlol - I am working on a new tool called molotov that is way faster (asyncio/aiohttp)

Boom can leverage it by wrapping its arguments to generate and run a molotov scenario - Added Issue #64
