### ISSUE TITLE
How to send files?

### ISSUE THREAD

**Issue by sunsided** [tarekziade/boom#61]
I would like to use Boom to load-test a server that requires file handling. I need to set both the `Content-Length`, as well as the file content as binary data. 

Since I want the file to be selected randomly from a directory to determine the average load in a common scenario, I thought using python callables with `-D py:...` would be an option, however I cannot make any sense of how to actually use it. Can you shed some light on it?

**Comment by tarekziade** [comment]
If you use:

```sh
-D py:mymodule.myfunc
```

It will try to import `mymodule.myfunc` and use that callable and call it with 3 arguments: method, url, and options.

That function needs to return the actual data send into the requests.

**Comment by sunsided** [comment]
Thanks! Is there a way to modify the request headers from the module?

**Comment by tarekziade** [comment]
closing, see #64
