### ISSUE TITLE
Question: plans for integrating with smwogger ?

### ISSUE THREAD

**Issue by Lucas-C** [tarekziade/boom#63]
Hi.

As you have also developped https://github.com/tarekziade/smwogger, I was wondering if you had any plan to integrate one with the other ? In order to easily load-test an API with a Swagger spec.

Regards

**Comment by tarekziade** [comment]
Why not that sounds like a good idea!

Right now I am trying to make sure it's easy to add Smwogger in whatever tool. The first one will be 
Molotov, which is a simple asyncio-based load test tool.

https://github.com/loads/molotov/

I was thinking once it's working, to extract its core and switch Boom to asyncio. It's much faster according to my tests.

**Comment by tarekziade** [comment]
closing, see #64
